### ISSUE TITLE
add external cache storage

### ISSUE THREAD

**Issue by ark-balandin** [SocketSomeone/nestjs-resilience#33]
It'd be nice to have an option to store state, failure count for each created object in a provided external storage like redis (implementation would be up to the user). This will ensure circuitbreaker has shared behaviour across deployed instances of the same app.

**Comment by Cliftonz** [comment]
I agree with @ark-balandin  I would make sure to add support for upstash too on top of Io redis.

**Comment by SocketSomeone** [comment]
@Cliftonz @ark-balandin Well, thank you for waiting! It was published in https://github.com/SocketSomeone/nestjs-resilience/releases/tag/2.0.0
