### ISSUE TITLE
Stale request object 

### ISSUE THREAD

**Issue by fhosen** [SocketSomeone/nestjs-resilience#487]
Hello there.

We are using this cool library you made to perform resilient calls from a GraphQL API to some other APIs.

To perform the HTTP Calls we made a NestJS Service that is just wrapping the [nestjs/axios](https://www.npmjs.com/package/@nestjs/axios) library and accessing the request object in order to extract some information we need to perform the request (such as a token).

The thing is, I found out that even though every provider is request scoped (because they depend the HttpService which is request scoped), when I use the `@UseResilience(new CircuitBreakerStrategy(someOptions))` in the methods that uses the HttpService we then get old requests objects (actually the first request object that hit the server).

Let me share some code:
Class that uses the CircuitBreaker

```typescript
import { HttpService } from '@addi/http-client/feature-http/nest';
import { Injectable, Logger } from '@nestjs/common';
import { BackendClient } from './client.interfaces';
import { CircuitBreakerStrategy, UseResilience } from 'nestjs-resilience';

export interface GetClientParams {
  clientId: string;
}

@Injectable()
export class ClientRepository {
  constructor(
    private readonly httpService: HttpService,
  ) {}

  private readonly logger = new Logger(ClientRepository.name);
  private readonly serviceBaseUrl = 'dummyurl.com';
  private static readonly GET_CLIENT_PATH = '/clients/{clientId}';

  @UseResilience(new CircuitBreakerStrategy())
  async getClient(params: GetClientParams): Promise<BackendClient> {
    const url = this.buildGetClientUrl(params);
    const { data } = await this.httpService.get<BackendClient>(url);
    return data;
  }

  private buildGetClientUrl(params: GetClientParams): string {
    return `${this.serviceBaseUrl}${ClientRepository.GET_CLIENT_PATH}`.replace(
      '{clientId}',
      params.clientId
    );
  }
}

```

HttpService constructor
```typescript
@Injectable({ scope: Scope.REQUEST })
export class HttpService implements IHttpService {
  private readonly logger = new Logger(HttpService.name);

  constructor(
    private readonly nestHttpService: NestHttpService,
    @Inject(MODULE_OPTIONS_TOKEN) protected readonly options: HttpModuleOptions,
    @Inject(CONTEXT) private context: { req: HttpRequest }
  ) {}

```

That `context.req` is stale when using `@UseResilience(new CircuitBreakerStrategy())` and it's fresh when avoiding it, this is also reflected on the context_id.

Any thoughts on what might be happening? Let me know if I can provide more information.

**Comment by SocketSomeone** [comment]
So, looks yours value was cached by  circuit breaker... Or maybe it broke request-scoped features.
Can you create minrepro for debug?

**Comment by fhosen** [comment]
> So, looks yours value was cached by circuit breaker... Or maybe it broke request-scoped features. Can you create minrepro for debug?

Hey @SocketSomeone , thank you for your response.

I've created [this mini repo](https://github.com/fhosen/nestjs-resilience-request-scope-bug), you can find in the description steps for reproducing the bug.

**Comment by SocketSomeone** [comment]
@fhosen Thank you!
https://github.com/SocketSomeone/nestjs-resilience/releases/tag/2.1.2

**Comment by fhosen** [comment]
> @fhosen Thank you! Fixed by https://github.com/SocketSomeone/nestjs-resilience/releases/tag/2.1.2

On the contrary, thank you for fixing this so quickly.
